language: php

php:
    - 7.1

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.1

env:
  - SYMFONY_VERSION="3.0.*" DEPENDENCIES=dev COMPOSER_FLAGS="--prefer-stable"

before_install:
  - composer self-update

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - php bin/console doctrine:database:create
  - php bin/console hautelook:fixtures:load
  - ./vendor/bin/simple-phpunit
  - ./vendor/bin/phpstan analyse src
  - ./vendor/bin/ecs check src